### ISSUE TITLE
Heading elements are not in a sequentially-descending order

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#1]
Running a lighthouse audit returns some accessibility issues regarding heading element order.

![Screen Shot 2020-12-02 at 17 10 45](https://user-images.githubusercontent.com/30320536/100906943-a5cdea00-34c1-11eb-8647-b95cadcc5aa3.png)

This will cause navigation issues for screen reader users. [This article explains in more detail why this is a problem](https://web.dev/heading-order/?utm_source=lighthouse&utm_medium=devtools).

We should fix the heading order to ensure a smooth navigation experience for screen readers.

**Comment by marcinwmichna** [comment]
Hi, can I work on that?

**Comment by marcinwmichna** [comment]
#16

**Comment by jrobind** [comment]
Closed by #15
