### ISSUE TITLE
Add viewport meta tag

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#10]
Because the site is missing a viewport meta tag, mobile devices actually render a scaled down desktop width page making content difficult to read and interact with. We should include one in the page head to fix this whilst making sure this passes a [lighthouse audit too](https://web.dev/viewport/?utm_source=lighthouse&utm_medium=devtools#how-the-lighthouse-viewport-meta-tag-audit-fails): 

For more information you can check the [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag).

**Comment by MLJBrackett** [comment]
Hey @jrobind I'd like to take this on! Assign me and I'll get started.

**Comment by jrobind** [comment]
All yours @MLJBrackett ! I'll get round to the PR review today
