### ISSUE TITLE
Fix modal text alignment

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#105]
There are some alignment issues with the modal lesson content.

**Steps to reproduce**:

1. Add new lesson
2. Click 'View' button on lesson card
![Screenshot 2021-03-04 at 16 22 11](https://user-images.githubusercontent.com/30320536/109995108-e37f2080-7d05-11eb-83e8-bd1f07458dfd.png)

**Comment by gaddscientist** [comment]
Hey I'd like to take this issue if you don't mind.  I have a pull request ready but I wanted to follow the contribution guidelines to get it assigned to me first.

**Comment by jrobind** [comment]
All yours! Thanks for dropping a comment and helping out!

**Comment by gaddscientist** [comment]
Thanks! Always happy to help.  Pull request is submitted.

**Comment by jrobind** [comment]
Closed by #107
