### ISSUE TITLE
issue in removing the lesson while editing it.

### ISSUE THREAD

**Issue by VIPIN24BOHRA** [jrobind/dev-jot#106]
To get the issue follow these steps :

- create a new single lesson.
- Click on the edit button.
- now click on the remove lesson button.
- now try to update the lesson it will not get updated or added.
- and after removing the lesson the submit button should show "Add lesson " instead of "Update lesson".
 

> hopefully I am able to convey the issue.

**Comment by VIPIN24BOHRA** [comment]
Solution :
**first solution:**

- hide the lesson when we are updating it so that the user can't delete it while updating. as there is no point in deleting while updating.

**second solution.**

- we can make some changes to the code so that after removing the lesson while editing it should not create a problem.


> we should also change the "Update lesson " to "Add lesson " on deleting the lesson while editing it. it will require just a few lines of code.

**Comment by jrobind** [comment]
Thanks for raising this issue! I'll try and reproduce this later today when I get some time. 

Feel free to take this on if you'd like 😄

**Comment by VIPIN24BOHRA** [comment]
Sure I would like to work on it.
