### ISSUE TITLE
Create footer component (React version)

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#110]
Create a Footer component that matches the default app version.

<img width="1436" alt="Screenshot 2021-03-24 at 13 13 53" src="https://user-images.githubusercontent.com/30320536/112316217-cc977280-8ca2-11eb-828a-176f7d9d48dd.png">

If you're looking for guidance you can check  `Header.jsx` [here](https://github.com/jrobind/dev-jot/blob/master/app-react/src/components/Header.jsx).

**Comment by ceelo777** [comment]
I'd like to take this issue on!

**Comment by jrobind** [comment]
All yours @ceelo777 😄
