### ISSUE TITLE
Create Lessons form component – React

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#114]
This ticket could cover the basic UI for the lesson form (check the live vanilla app to see). 
![Screenshot 2021-04-07 at 20 46 17](https://user-images.githubusercontent.com/30320536/113924926-52a6d380-97e2-11eb-94b7-8206f384e748.png)

We need to make sure the markup is accessible i.e. correct HTML5 elements, keyboard navigation works. We also need to ensure styling is consistent with the live vanilla version.

We will need to persist submitted lesson data to local storage and eventually sync this up with other app components. We can create a separate issue for this if necessary and just stick to the UI/markup side of things for now – I'm keen to get the React side of things moving.

**Comment by muzamil301** [comment]
hello @jrobind how can I start working on it I mean I need repo to contribute

**Comment by jrobind** [comment]
Hey @muzamil301, feel free to pick this up. You'll need to fork the repo to work on this. If you're completely new to open source contributions I'd recommend you follow [this guide](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github).

Also make sure you have a read through `CONTRIBUTING.md` within the project root 😄

**Comment by muzamil301** [comment]
hello @jrobind you are right I am new to open source contribution. I will read the guide for sure then I will work on it  😄
