### ISSUE TITLE
Prevent homepage scroll 

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#12]
Currently you can scroll the homepage content which I think looks a bit odd. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/30320536/101287747-18a0d300-37ea-11eb-8e80-59436c3964e8.gif)

For now we should prevent scrolling and have content fill 100% viewport height.

**Comment by Jwright707** [comment]
I would like to take a look into this issue.

**Comment by jrobind** [comment]
All yours @Jwright707

**Comment by jrobind** [comment]
Closed by #12
