### ISSUE TITLE
Add Open Graph meta tags and improve 'description' meta tag

### ISSUE THREAD

**Issue by louiscarnell** [jrobind/dev-jot#121]
There aren't any Open Graph meta tags or a good description of the site within the `<meta name="description"/>` tag. This makes the site look a bit plain when sharing online or when it's listed in search results (as can be seen with the preview below from https://metatags.io/).

I would like to work on this (to learn / practice contributing to GitHub).

![screenshot of metatags io preview](https://user-images.githubusercontent.com/54234679/117568343-ac3b4000-b0b7-11eb-8aab-259e408d8f14.png)

**Comment by jrobind** [comment]
Hi @louiscarnell thanks for opening this issue. Feel free to work on this 😄
