### ISSUE TITLE
Tags are not stored in local storage

### ISSUE THREAD

**Issue by akosbalasko** [jrobind/dev-jot#126]
Hi! 
As I see in Local Storage, tags are not stored in the JSON data, however I set a red-tag. I'm not sure if it matters, but I created a lesson with no tag and then updated it by setting a red-tag and clicked to update. 

Expected behaviour: they should :) 

<img width="655" alt="Screenshot 2021-06-01 at 8 04 39" src="https://user-images.githubusercontent.com/11886731/120274437-22deee00-c2b0-11eb-839e-81df277cafef.png">

**Comment by jrobind** [comment]
Thanks for raising this issue @akosbalasko. Great spot. Feel free to pick this up if you want 😄

**Comment by akosbalasko** [comment]
Thanks @jrobind , challenge accepted! :)
