### ISSUE TITLE
Remove cursor styling from lesson cards

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#13]
Lesson cards have `cursor: pointer` applied which gives the user the impression that the cards should be clickable but they are not.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/30320536/101288006-ca8ccf00-37eb-11eb-8ba6-83f51691486f.gif)

We should remove the cursor styling.

**Comment by lkruger93** [comment]
Hi, can I work on this and do it a better way this time?  thanks for the feedback from earlier!

**Comment by jrobind** [comment]
It's all yours - you're welcome 😄

**Comment by jrobind** [comment]
Closed by #17
