### ISSUE TITLE
Lesson content extends beyond container when viewing 

### ISSUE THREAD

**Issue by Blargian** [jrobind/dev-jot#131]
When viewing a lesson if the content height exceeds the height of the container then it extends beyond the container. See [here](https://imgur.com/a/9KX19Q9) for example. 

A simple fix might be to add a scrollbar to the content view area so that the user can just keep scrolling down if the content exceeds the container height.

**Comment by jrobind** [comment]
Thanks for raising this issue! Great spot. Adding a vertical scrollbar seems like the best fix. Feel free to take this on if you'd like 😄

**Comment by Blargian** [comment]
@jrobind Great, you can assign this to me and I'll do it as soon as I'm done with the export to .md stuff 👍 by the way is the React version of the app at the same stage of development as the vanilla JS app?

**Comment by jrobind** [comment]
> @jrobind Great, you can assign this to me and I'll do it as soon as I'm done with the export to .md stuff 👍 by the way is the React version of the app at the same stage of development as the vanilla JS app?

Will do! No rush at all so take your time. It's not, it's some way behind. There are a couple of individuals working on it intermittently but it could do with some more focused work. There's a lot of freedom with it too, it doesn't have to be a like-for-like rebuild, we could add different features.

**Comment by jrobind** [comment]
Closed by #136
