### ISSUE TITLE
Implement app mobile design

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#18]
Although the app works on mobile, currently it's only set up for desktop users. We should update the app to work on smaller viewports. Maybe the editor and lesson grid should stack into a single column? This issue is a little vague so there is scope to do lots with this.

If anyone wants to pick this up maybe it would be best to have a discussion about next steps here.

**Comment by nimiakinleye** [comment]
I'll be willing to pick this up!

**Comment by nimiakinleye** [comment]
> Although the app works on mobile, currently it's only set up for desktop users. We should update the app to work on smaller viewports. Maybe the editor and lesson grid should stack into a single column? This issue is a little vague so there is scope to do lots with this.
> 
> If anyone wants to pick this up maybe it would be best to have a discussion about next steps here.

I'll be willing to pick this up!

**Comment by jrobind** [comment]
Go for it @nimiakinleye 😃  💪

**Comment by jrobind** [comment]
Hey @nimiakinleye just wondered how you're getting on with this?

**Comment by nimiakinleye** [comment]
> Hey @nimiakinleye just wondered how you're getting on with this?

I've not been able to work on it, the bug I told you prevented me from working on the project is yet to be resolved

**Comment by jrobind** [comment]
It should be working fine now 😄  Are you able to clone the repo again and follow the set up instructions? Let me know if you still want to carry on with this, otherwise I can let someone else have a go. Let me know what you'd like to do 😃

**Comment by nimiakinleye** [comment]
> It should be working fine now 😄  Are you able to clone the repo again and follow the set up instructions? Let me know if you still want to carry on with this, otherwise I can let someone else have a go. Let me know what you'd like to do 😃 

For sure I'd like to carry on with it. Okay, I'll try cloning again. Let's see how that goes, hopefully it'll work😃

**Comment by jrobind** [comment]
Awesome! Feel free to ping here or on DIscord if you're still having issues 😄

**Comment by nimiakinleye** [comment]
> Awesome! Feel free to ping here or on DIscord if you're still having issues 😄 

Alright, thank you sir!😉

**Comment by jrobind** [comment]
I've merged this, thanks @nimiakinleye 👍
