### ISSUE TITLE
Add link option to editor toolbar

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#19]
It would be nice to include an 'add link' option in the toolbar editor.

![Screen Shot 2020-12-07 at 08 56 41](https://user-images.githubusercontent.com/30320536/101330130-2c8c1980-386a-11eb-936c-c80aa652544c.png)

**Comment by MSoup** [comment]
I'd like to give this a go.

**Comment by jrobind** [comment]
It's all yours @MSoup 😃

**Comment by MSoup** [comment]
Posting an update - I got the link (and image upload) option into the toolbar following the quilt module documentation, but the pop up UI isn't playing well with our current site set up. I'll need some time to figure out how to figure this out before submitting this.

**Comment by MSoup** [comment]
Update2: Finished feature and fixed UI bug. I have no idea how to make the pull request though and googling isn't helping me right now. Maybe I will figure it out soon but I am getting permission denied even if I make a new branch and try to push it.

**Comment by jrobind** [comment]
Thanks for the updates - great job! 

Hopefully you'll get things working now per our discussion on Discord.

**Comment by jrobind** [comment]
Closed by #36
