### ISSUE TITLE
Refactor application to use Async Await

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#20]
This refactor will make the asynchronous code a little easier to read. The [MDN docs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await) are a good place to start if you need a refresh.

**Comment by buigabor** [comment]
Hi! Can I take this on?:)

**Comment by jrobind** [comment]
Go for it @buigabor 🚀

**Comment by jrobind** [comment]
Closed by #49
