### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#21]
Let's add a [favicon](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Adding_custom_icons_to_your_site)!

**Comment by groggilsoft** [comment]
(Eyeraker)
I would like to work on this.

**Comment by jrobind** [comment]
All yours 😄

**Comment by jrobind** [comment]
Closed by #30
