### ISSUE TITLE
Cannot add new lesson after editing and removing previous lesson

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#22]
If I edit a particular lesson and then delete it, if I then try to add a new lesson it fails silently and the lesson isn't added:

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/30320536/101331967-9b6a7200-386c-11eb-897f-bddc8e532532.gif)

If you're struggling to debug this please follow [this code reading process](https://www.thefrontendcoach.com/blog/how-to-read-code).

**Comment by furkanmutlu** [comment]
I would like to work on this issue.

**Comment by furkanmutlu** [comment]
Created PR: #40

**Comment by jrobind** [comment]
Just merged. Thanks!
