### ISSUE TITLE
After editing a lesson, if you immediately create a new lesson it overwrites whichever one you edited.

### ISSUE THREAD

**Issue by groggilsoft** [jrobind/dev-jot#23]
**Note: Reloading the page inbetween editing and creating a new lesson will cause the issue not to happen.** 

![dev-jot — Mozilla Firefox 2020-12-07 09-25-57](https://user-images.githubusercontent.com/65983879/101363601-9955e280-386f-11eb-972f-c5fe16e4fc22.gif)

**Comment by seunggyupark** [comment]
I'll take a look at this, if you don't mind!

**Comment by jrobind** [comment]
All yours 😄
