### ISSUE TITLE
Convert pre-auth Google sign in div to button

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#25]
Currently the pre-auth sign in button isn't actually a `button` element it is a `div`.

![Screen Shot 2020-12-07 at 15 52 02](https://user-images.githubusercontent.com/30320536/101372794-2d41a180-38a4-11eb-826e-761433be6b69.png)

For accessibility reasons, we should either convert this to a `button` element or keep this as a `div` but make sure this is accessible for screen readers. (tip, Google search for aria attributes & roles). Either way, make sure the styling remains consistent.

**Comment by MaheshMadushan** [comment]
Hi, I like to work on this one. This is first time I'm contributing :)

**Comment by furkanmutlu** [comment]
I would like to fix this issue

**Comment by jrobind** [comment]
Go for it @furkanmutlu!

**Comment by furkanmutlu** [comment]
@jrobind thank you, I already created PR last night :)

**Comment by jrobind** [comment]
Closed by #29
