### ISSUE TITLE
Improve JavaScript error handling

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#3]
Currently any JavaScript errors that are caught are being printed to the console with `console.log` or `console.error`.

I think it will be more useful for the user to receive some feedback if a request or action fails.

For instance, if a user attempts to remove/delete a lesson and this request fails the lesson card remains on the screen and the process fails silently which is confusing for the user.

**Comment by ehowden** [comment]
Hello! My partner (@iyerm2000) and I would like to take this issue! We are Computer Science students at the University of Michigan and are working on a contribution project.

**Comment by jrobind** [comment]
> Hello! My partner (@iyerm2000) and I would like to take this issue! We are Computer Science students at the University of Michigan and are working on a contribution project.

Hey! It's all yours. Thanks for picking this up, let me know if you have any questions 😄

**Comment by iyerm2000** [comment]
Hi! I am ready to create a PR. Can I be assigned to the issue too? I am @ehowden's partner!

**Comment by jrobind** [comment]
Closed by #117
