### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#32]
I think [prettier](https://prettier.io/) would be a good fit. It would save beginners having to worry excessively about linting. With prettier all the formatting is handled for you. 

Open to discussion/suggestions on this!

**Comment by mamadou-diallo** [comment]
I can take care of this.

**Comment by jrobind** [comment]
Go for it @mamadou-diallo 😄

**Comment by mamadou-diallo** [comment]
@jrobind Hey ! Any sort of specific rules that you would like for me to apply?

**Comment by jrobind** [comment]
Aside from `"tabWidth": 2`, it's totally up to you! Whatever you feel makes sense. We can always update the linting rules at a later date

**Comment by jrobind** [comment]
closed by #51
