### ISSUE TITLE
Convert site to Progressive Web App

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#33]
As a PWA the site would have a really cool offline experience and also have the look and feel of a native app. We have the manifest already set up, and the site is served over https so the last thing is to ensure the app is installable. To do this, we need to have a registered service worker which will allow the app to work offline.

For information on PWAs please read through the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) 
[here is a specific article](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Offline_Service_workers) on service workers for PWAs

**Comment by buigabor** [comment]
I would like to tackle this! Never did anything like this before!:D

**Comment by jrobind** [comment]
Go for it @buigabor 😃

**Comment by jrobind** [comment]
Closed by #71
