### ISSUE TITLE
Create gulp boilerplate/setup

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#34]
It would be nice to improve development workflow and automate some tasks such as optimising assets like CSS, JavaScript, and images with [gulp](https://gulpjs.com/).

Gulp is considered a build tool along with the likes of grunt and broccoli. Gulp config tends to be a little shorter and easier to write (imho) so it might be the best build tool for beginners. Open for discussion of course!

As a starting point, whoever takes on this task could focus on getting gulp set up. We could raise separate issues to tackle asset compression/optimisation etc.

**Comment by ceelo777** [comment]
Is this for React or Vanilla version of the app? Or maybe both?

**Comment by jrobind** [comment]
> Is this for React or Vanilla version of the app? Or maybe both?

This was intended for the vanilla version. I think for the React version seeing as we're using CRA it makes more sense to let webpack handle asset optimisation. If we need to override webpack config we could use something like [craco](https://github.com/gsoft-inc/craco).

**Comment by ceelo777** [comment]
> > Is this for React or Vanilla version of the app? Or maybe both?
> 
> This was intended for the vanilla version. I think for the React version seeing as we're using CRA it makes more sense to let webpack handle asset optimisation. If we need to override webpack config we could use something like [craco](https://github.com/gsoft-inc/craco).

Sounds good - I added a configuration file for the vanilla version - I'm not sure exactly what functionality we want for both pack-js and pack-css so I just packed all the assets into a build folder for now - we should probably create future issues to slowly build the functionalities for both functions from the bottom up.

**Comment by jrobind** [comment]
> > > Is this for React or Vanilla version of the app? Or maybe both?
> > 
> > 
> > This was intended for the vanilla version. I think for the React version seeing as we're using CRA it makes more sense to let webpack handle asset optimisation. If we need to override webpack config we could use something like [craco](https://github.com/gsoft-inc/craco).
> 
> Sounds good - I added a configuration file for the vanilla version - I'm not sure exactly what functionality we want for both pack-js and pack-css so I just packed all the assets into a build folder for now - we should probably create future issues to slowly build the functionalities for both functions from the bottom up.

Sounds good! Thanks for setting this up. /build sounds fine, we can update/iterate at a later date. I'll review the PR now!
