### ISSUE TITLE
Selected font size does not apply to "view lesson" view

### ISSUE THREAD

**Issue by marcinwmichna** [jrobind/dev-jot#38]
As the title says: creating new lesson and selection font size does apply to lesson overview but **not** to "view lesson" view.
![testing](https://user-images.githubusercontent.com/49107774/101635359-26449b80-3a2a-11eb-9318-5d2a7294417d.PNG)

**Comment by jrobind** [comment]
Good spot, thanks for raising the issue.

**Comment by groggilsoft** [comment]
I can take this one

**Comment by jrobind** [comment]
All yours 😄

**Comment by jrobind** [comment]
Closed by #94
