### ISSUE TITLE
Prevent update lesson button text from wrapping

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#4]
The update lesson button text wraps throwing out the button styling. 

![Screen Shot 2020-12-03 at 22 46 08](https://user-images.githubusercontent.com/30320536/101097598-5ec32000-35b9-11eb-910f-0c6b89da845e.png)

**Comment by furkanmutlu** [comment]
I would like to work on this bug. Could you please explain me more about the issue and repro steps?  What do you mean by text wraps throwing out the button styling?

**Comment by jrobind** [comment]
Awesome go for it!

Sure. Essentially, there should be no line break, the button text should be on one line >> UPDATE LESSON
I'm able to produce this by:

1. Creating a lesson
2. Clicking on a lesson edit button

This is on: 

**Mac OS X Yosemite**
**Chrome 86**

**Comment by furkanmutlu** [comment]
@jrobind  Created PR: #39

**Comment by jrobind** [comment]
Closed by #39
