### ISSUE TITLE
Move Quill and Firebase JS initialisation to its own file

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#41]
Currently the quill and firebase initialisation and configurations are located within a `script` in the HTML. 

It would be better to have all of the JS grouped together, better still, we could start to modularise the JS using JS modules and have this config and initialisation moved into its own file.

**Comment by MSoup** [comment]
I'd like to tackle this! First time modularizing.

**Comment by jrobind** [comment]
Go for it @MSoup!

**Comment by MSoup** [comment]
Done and PR posted. One thing that had me a little bit uncertain was that I split firebase and quill into their own respective modules, but they're both small pieces of code, so maybe it would have been cleaner to just have an init file that encompasses both. On the other hand, it might be much faster to debug once our codebase gets big when it's separated like this.

**Comment by jrobind** [comment]
I missed this comment! I guess if the config and initialisation becomes more complex we can move them back out into separate files. Nice job!

Closed by #56
