### ISSUE TITLE
Fix lesson card close btn spacing 

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#45]
We could do with a little more space below the lesson close button and the lesson content container:

![Screen Shot 2020-12-10 at 09 27 55](https://user-images.githubusercontent.com/30320536/101753098-2b592780-3aca-11eb-895c-82179ba35514.png)

**Comment by marcinwmichna** [comment]
Let me quick fix that.

**Comment by marcinwmichna** [comment]
#66

**Comment by jrobind** [comment]
Closed by #66
