### ISSUE TITLE
Set up testing environment

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#46]
I'd recommend using [jest](https://jestjs.io/), but open to discussions on this.

This issue could cover just the testing setup and configuration.

In terms of actually writing some meaningful tests for our code, this will probably require a bit of extra work and refactoring. We might need to move our JS logic into a class which will make testing methods/functionality much easier.

**Comment by mamadou-diallo** [comment]
I'll take care of this

**Comment by jrobind** [comment]
Thanks! 👍

**Comment by jrobind** [comment]
Closed by #52
