### ISSUE TITLE
Prevent users from creating lessons with no notes

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#47]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/30320536/101797036-7c384280-3b01-11eb-89ff-27703a8b6954.gif)

**Comment by edXmO** [comment]
Hi! Can I tackle this?

**Comment by jrobind** [comment]
Sure thing! Go for it!

**Comment by edXmO** [comment]
I got it working. But I have a question/suggestion. Managed to prevent the user from creating a lesson with no lesson text. So i thought it might be a good idea to prevent them from creating lessons containing only whitespaces too.

In that last case, when testing it, adding an only whitespaces lesson makes the placeholder empty/blank. 

So, should I add again the current "Add some lesson notes!" or something different to inform about the whitespaces. 

Thanks!

**Comment by jrobind** [comment]
Good point @edXmO. I agree, we should prevent lesson with only whitespace from being created too. 

How are you preventing the user from submitting a lesson? Are we displaying an error message? I think it would be nice to have a generic message that covers both cases

Thanks for taking this on 😄

**Comment by jrobind** [comment]
Btw just reviewed your PR. We can hold off on the error message for now. How about we get your current PR merged in and then we can raise a new issue to address this?

**Comment by edXmO** [comment]
Thank you so much for the feedback! Good idea, I'll first concentrate on solving all posible cases for the PR and then I'll address the error message.

**Comment by jrobind** [comment]
You're very welcome! Awesome 👍

**Comment by jrobind** [comment]
Closed by #58
