### ISSUE TITLE
typo in Current State paragraph of readme file

### ISSUE THREAD

**Issue by VIPIN24BOHRA** [jrobind/dev-jot#48]
In the Current State paragraph of the readme file, in the 4th line, there is a typo in the active link instead of live verson it must be " live version"

**Comment by jrobind** [comment]
Thanks for raising this. Good spot - feel free to pick this up if you want to. No worries if not!

**Comment by VIPIN24BOHRA** [comment]
yeah, I  am up for this. plz label it "in-progress"

**Comment by jrobind** [comment]
Closed by #50
