### ISSUE TITLE
Use ES6 modules to modularise JavaScript

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#5]
Currently all of the JavaScript code lives in [one file](https://github.com/jrobind/dev-jot/blob/master/public/js/index.js).

It would be nice to move the code into separate modules which will encourage reusability and improve maintainability. Modules should be small pieces of code with independent functionalities which means that they should be easier to test too.

The code could be separated out depending on it's function. If you're unfamiliar with JavaScript modules then I'd recommend reading the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).

**Comment by Jmiccolo** [comment]
Going to try my hand at this.

**Comment by jrobind** [comment]
All yours @Jmiccolo!

**Comment by Jmiccolo** [comment]
Just want to make sure that I can change the name of firebase_quill_init.js to just quill_init.js to avoid confusion that firebase might be necessary for it. Also just removed firebase to its own folder as it is not referenced anywhere.

**Comment by jrobind** [comment]
That's absolutely fine @Jmiccolo. I've just recently raised a ticket to remove the firebase code anyway! Thanks for checking 😄

**Comment by jrobind** [comment]
Closed by #95
