### ISSUE TITLE
Clear button should appear when adding/creating a lesson too

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#54]
Currently when you edit a lesson the clear button appears:

![Screen Shot 2020-12-12 at 16 48 40](https://user-images.githubusercontent.com/30320536/101989660-eab00880-3c99-11eb-8ad7-d351b9a9b976.png)

It would be nice if there was the option to also clear content when a user is creating/adding a new lesson.

**Comment by edXmO** [comment]
Hi! I think I can do this :)

**Comment by jrobind** [comment]
All yours :)

**Comment by edXmO** [comment]
Hi! I've been thinking on the approach. Since the user can only send a lesson if it has a title, what I did is, clear button appears when user clicks on lesson title. 

* Should I also consider the text box?

Also I thought that instead of adding it via eventListener, maybe it would be a better idea to write a function, so if needed in other place can be reused. 

Let me know. Thanks!

**Comment by jrobind** [comment]
I think this sounds like a good approach! It would be nice for the button to appear once the user interacts with the editor content field too. I guess we also need to make sure that if the title field and content field are both empty then the clear button should disappear.

What do you think?

**Comment by edXmO** [comment]
Yeah, that was what I was thinking. Sorry, I was working on it and forgot to reply. 

What I did was created a function that handles the hidden attribute of the clear button atacched to the window onload event. 

This is what i covered so far:

* Clear appears when mousing over the form, even if form is empty.
* When mousing out of the form, and if both fields are empty, clear button disappears.
* When mousing out of the form if any of the fields has at least one character, clear button stays.
* If I write a title and a lesson note and then delete both, clear button disappears when mouse leaves the form. Else, stays. 

Let me know if I missed any more use cases. 

Thanks!.

**Comment by jrobind** [comment]
That sounds spot on @edXmO. It doesn't have to be perfect, if we miss some use cases we can always raise another issue. 

Btw, you're doing a really good job of documenting your process 👍 

Thanks

**Comment by jrobind** [comment]
Closed by #68
