### ISSUE TITLE
Add a lessons count/total

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#55]
I think it would be cool to have the total number of lessons visible to the user.

Maybe we could place the total near the Lessons heading:

![Screen Shot 2020-12-12 at 16 51 35](https://user-images.githubusercontent.com/30320536/101989745-75910300-3c9a-11eb-9967-ae7b90b6a4f3.png)

Open for suggestions on what this count/total would look like!

**Comment by AdnCodez** [comment]
Hey, I have finished this one, is this what you wanted 
![Screenshot from 2020-12-17 19-11-47](https://user-images.githubusercontent.com/20237313/102526344-cdb17600-409b-11eb-970f-d029661c72c6.png)
![Screenshot from 2020-12-17 19-11-39](https://user-images.githubusercontent.com/20237313/102526346-cee2a300-409b-11eb-898b-e32a64933aab.png)

**Comment by jrobind** [comment]
This looks good @AdnCodez. I'm not sure if we need a count for when there are no lessons seeing as the 'No lessons' text handles this. We could maybe add a hyphen between 'Lessons' and the number just so it looks a little cleaner.

What do you think?

**Comment by AdnCodez** [comment]
Okay, sounds good I will adjust that, maybe the comma is not necessary it will make things a bit cluttered imo :)

**Comment by jrobind** [comment]
Closed by #73
