### ISSUE TITLE
Add lesson tags

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#59]
Links to #62

As part of the lesson tag filter feature, a user should be able to filter lessons by tag(s). This issue should cover just the JS implementation of adding tags to lessons.

Hint: you can add the tag field/property somewhere within `addLesson()` and you can check to see if this works within `renderLessons`.

**Comment by MSoup** [comment]
I'll try this issue!

**Comment by jrobind** [comment]
Go for it @MSoup 😄

**Comment by jrobind** [comment]
Closed by #93
