### ISSUE TITLE
Update 404.html

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#67]
Currently this is the default Firebase 404 markup.

![Screen Shot 2020-12-16 at 15 01 10](https://user-images.githubusercontent.com/30320536/102365546-95346e00-3faf-11eb-9acf-e20cdc1d2c4b.png)

Let's update this so the page is more consistent with the rest of the site design.

**Comment by chhatrapalsinhzala007** [comment]
hyyy

let's work on this together.

**Comment by jrobind** [comment]
Hey @chhatrapalsinhzala007 it's all yours 😄 

[This is the file you need to update](https://github.com/jrobind/dev-jot/blob/master/app-main/public/404.html)

**Comment by chhatrapalsinhzala007** [comment]
Hyy @jrobind.
 I will complete this as soon as possible.

**Comment by jrobind** [comment]
Awesome. No rush @chhatrapalsinhzala007 – take your time with it!

**Comment by chhatrapalsinhzala007** [comment]
hyy @jrobind i have submitted pull request please check it out. and please let me know if you want any other changes.

**Comment by jrobind** [comment]
Hey @chhatrapalsinhzala007 are you still working on this? Otherwise I'll open this back up.

**Comment by jrobind** [comment]
I'm going to open this one back up

**Comment by ehowden** [comment]
Was this resolve by PR #76 ?

**Comment by jrobind** [comment]
No, this ready to work on. Thanks for reminding me, I forgot to close #76

**Comment by ehowden** [comment]
I'd be happy to take it on with @iyerm2000 !

**Comment by jrobind** [comment]
Go for it! 👍

**Comment by jrobind** [comment]
Closed by #116
