### ISSUE TITLE
Add EditorConfig

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#69]
Adding an `.editorconfig` file will help to maintain consistent coding styles for contributors working on the project across various editors and IDEs.

Here is an example config:

```
# stop .editorconfig files search on current file.
root = true

# Unix-style newlines with a newline ending every file
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = tab
indent_size = 2
trim_trailing_whitespace = true
```

Please see the [docs](https://editorconfig.org/) for more information

**Comment by RoseKimball** [comment]
Hi, I can work on this issue
