### ISSUE TITLE
[PWA] Can't fetch manifest icon

### ISSUE THREAD

**Issue by buigabor** [jrobind/dev-jot#72]
The application can't fetch the manifest icon. Probably the paths are not correct in the site.manifest file.

<img width="443" alt="Screenshot 2020-12-17 at 16 30 21" src="https://user-images.githubusercontent.com/65706872/102508028-380aec00-4085-11eb-8941-a57b4e5b4c32.png">

**Comment by jrobind** [comment]
Good spot! Thanks!

**Comment by buigabor** [comment]
Can I fix this myself? I am kinda into PWA right now :D

**Comment by jrobind** [comment]
Of course! All yours 👍
