### ISSUE TITLE
Align lesson count

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#78]
Currently the lesson count alignment is a little off relative to the "Lessons" text:

![Screen Shot 2020-12-21 at 12 03 17](https://user-images.githubusercontent.com/30320536/102775388-abae4100-4384-11eb-9475-ea13189377ce.png)

**Comment by medhavibasera** [comment]
I would like to work on this!

**Comment by jrobind** [comment]
All yours @medhavi11 👍

**Comment by jrobind** [comment]
Closed by #85
