### ISSUE TITLE
Update document <head> in React app

### ISSUE THREAD

**Issue by lucievr** [jrobind/dev-jot#80]
This issue covers updating the document head, including meta tags, links and title in the React app to match the attributes of the main dev-jot app as seen here: https://github.com/jrobind/dev-jot/blob/master/app-main/public/index.html

[Happy to take this on to get the ball rolling but for future issues I'll give space to someone else 😉 ]

**Comment by jrobind** [comment]
Thanks for raising the issue. It's all yours! 

Open and work on as many issue as you want to – the React side of the app needs lots of work 😄

**Comment by lucievr** [comment]
Okay, thanks 😄
