### ISSUE TITLE
Notes should be scrollable in the preview pane

### ISSUE THREAD

**Issue by MSoup** [jrobind/dev-jot#86]
Instead of the text simply being cut off, it would be nice to be able to scroll through the text preview. The whole text is being loaded anyway, isn't it? If it isn't, then I guess we save some bytes (potentially kilobytes at best) of data by only having the preview show a max limit, but if it is, then a scrollable implementation would be easier than having to manually click "view lesson." (Imagine if you had 30+ lessons)

![preview](https://user-images.githubusercontent.com/19704779/103112575-c2f97100-4699-11eb-959e-31f8d9c71684.PNG)

**Comment by jrobind** [comment]
Thanks for raising this. Totally agree, this will become really annoying fast, especially if lesson content looks similar. I *think* the whole text is being loaded.

yep, looks like it's the entire lesson content:

https://github.com/jrobind/dev-jot/blob/master/app-main/public/js/index.js#L241

**Comment by nimiakinleye** [comment]
Nice Idea, I decided to work on this since I didn't find an 'in progress' tag.

**Comment by jrobind** [comment]
Thanks @nimiakinleye, I'll review the PR later today 😃

**Comment by jrobind** [comment]
Closed by #91
