### ISSUE TITLE
Add button hover effect

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#9]
There are no hover effects for buttons across the app. 

Other than `cursor: pointer`, I think it would be nice to have a cool global hover effect. You can make it as fancy as you like, just make sure the hover effect is consistent across all buttons.

**Comment by Niaz-Ul-Haque** [comment]
Can i  get assigned to this? im interested in working with this issue and come up with solutions. Thank you

**Comment by jrobind** [comment]
@Niaz-Ul-Haque go for it!

**Comment by Niaz-Ul-Haque** [comment]
Thank you for  the opportunity

**Comment by Niaz-Ul-Haque** [comment]
[#11](https://github.com/jrobind/dev-jot/pull/11)

**Comment by jrobind** [comment]
Hey @Niaz-Ul-Haque, are you still working on this?

**Comment by jrobind** [comment]
This is now open for someone else to work on 😄

**Comment by medhavibasera** [comment]
I would like to work on this.

**Comment by jrobind** [comment]
All yours 😄

**Comment by jrobind** [comment]
Closed by #102
