### ISSUE TITLE
Remove auth markup, logic, and styling from both default & React app

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#92]
The app originally used Firebase to authenticate users via Google profile so lessons could be persisted using Firestore. Firebase has been removed from the project and now lessons are persisted within the browser using the local storage API.

We need to remove the logic, markup & styles associated with the authentication. We need to do this across both apps, otherwise this will confuse contributors and it might seem like there's hidden functionality when there isn't. For example, in the default app [here's where](https://github.com/jrobind/dev-jot/blob/master/app-main/public/index.html#L62) we need to remove the button markup.

**Comment by Jmiccolo** [comment]
Just want to make sure. No reason to break up the firebase javascript as it is not being used at this moment(separated it out to its own folder for later use if necessary). Also the firebase_quill_init.js is only referencing the quill.js library. Should we remove the firebase prefix for less confusion on that(I was confused about its use).

**Comment by lucievr** [comment]
Happy to take this on ✋

**Comment by jrobind** [comment]
Go for it 👍
