### ISSUE TITLE
Clicking clear button in edit view reverts text for submit button

### ISSUE THREAD

**Issue by jrobind** [jrobind/dev-jot#96]
If you edit a lesson and click the CLEAR button to remove the form input text, it also reverts the submit button text from 'UPDATE LESSON' to 'ADD LESSON'. It should remain as 'UPDATE LESSON'.

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/30320536/103888947-8b4ce900-50dd-11eb-9fa0-fed9358b2a65.gif)

**Comment by VIPIN24BOHRA** [comment]
hi @jrobind I would like to handle it, well I have fixed the problem. just I have to make a pull request.

**Comment by jrobind** [comment]
Awesome, go for it! 👍

**Comment by jrobind** [comment]
Closed by #104
